# Generated by Django 3.0.4 on 2020-04-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Image', models.ImageField(upload_to='')),
                ('Price', models.FloatField()),
                ('Discount', models.CharField(max_length=80)),
                ('Slug', models.SlugField(max_length=80)),
                ('Brand_Name', models.CharField(max_length=80)),
                ('Category_Name', models.CharField(max_length=80)),
                ('Colour', models.CharField(max_length=80)),
                ('Size', models.CharField(max_length=80)),
                ('Weight', models.FloatField()),
                ('Discription', models.TextField(max_length=80)),
                ('Modify_date', models.DateTimeField()),
                ('Expiry_date', models.DateTimeField()),
                ('Create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.ImageField(upload_to='pics')),
                ('Sitemoto', models.TextField(max_length=100)),
                ('Phonenumber', models.TextField(max_length=31)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField(max_length=150)),
                ('Facebook', models.URLField()),
                ('Twitter', models.URLField()),
                ('Googlepls', models.URLField()),
                ('linkedin', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phonenumber', models.TextField()),
                ('Password', models.CharField(max_length=50)),
                ('RePassword', models.CharField(max_length=50)),
            ],
        ),
    ]
